spring:
  application:
    name: apigateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/products/**

            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/users/**

            - id: order-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/orders/**, /api/cart/**
#what happening above is api gateway pointing the matching path to their corresponding uri:-
#http://localhost:8181/api/cart ----> http://localhost:8080/api/cart

#logging:
#  level:
#    root: info
#    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
#    org.springframework.cloud.gateway: trace

server:
  port: 8181

#spring:
#  application:
#    name: apigateway
#  cloud:
#    gateway:
#      routes:
#        - id: product-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/products/**
#        - id: user-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/users/**
#        - id: order-service
#          uri: http://localhost:8080
#          predicates:
#            - Path=/api/orders/**, /api/cart/**
#
#server:
#  port: 8181
